twrp: Use `OUT_DIR`
 * `OUT` usage is deprecated now. Use `OUT_DIR` instead. 

```
error: OUT is obsolete. Use OUT_DIR instead. See https://android.googlesource.com/platform/build/+/master/Changes.md#OUT.
```